version: '3'

services:
  node:
    build: .
    restart: unless-stopped
    command: "npm run start"
    working_dir: /usr/src/app/
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  proxy:
    image: nginx:alpine
    container-name: web-proxy
    restart: unless-stopped
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - node
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
