version: '3'
services:
  node:
    build: .
    restart: always
    command: "npm run start"
    working_dir: /usr/src/app/
    environment:
      - NODE_ENV=production
    expose:
      - '3000'
    ports:
      - "3000:3000"
